"""add customer info to tokens

Revision ID: 85e0b7c745b6
Revises: 5b246e967260
Create Date: 2026-03-06 18:36:15.550732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e0b7c745b6'
down_revision: Union[str, None] = '5b246e967260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    
    # 1. Add columns as nullable=True
    op.add_column('tokens', sa.Column('customer_name', sa.String(length=120), nullable=True))
    op.add_column('tokens', sa.Column('customer_age', sa.Integer(), nullable=True))
    op.add_column('tokens', sa.Column('customer_phone', sa.String(length=20), nullable=True))
    
    # 2. Backfill existing tokens
    op.execute("UPDATE tokens SET customer_name = 'Unknown' WHERE customer_name IS NULL")
    op.execute("UPDATE tokens SET customer_phone = 'Unknown' WHERE customer_phone IS NULL")
    
    # 3. Alter columns to set nullable=False
    op.alter_column('tokens', 'customer_name', nullable=False)
    op.alter_column('tokens', 'customer_phone', nullable=False)
    
    op.create_index(op.f('ix_tokens_status'), 'tokens', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_status'), table_name='tokens')
    op.drop_column('tokens', 'customer_phone')
    op.drop_column('tokens', 'customer_age')
    op.drop_column('tokens', 'customer_name')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'])
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
