"""add address and phone to organization

Revision ID: 96f979b2a7fd
Revises: 85e0b7c745b6
Create Date: 2026-03-06 20:01:09.176110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '96f979b2a7fd'
down_revision: Union[str, None] = '85e0b7c745b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('address', sa.String(length=1000), nullable=True))
    op.add_column('organizations', sa.Column('phone_number', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'phone_number')
    op.drop_column('organizations', 'address')
    # ### end Alembic commands ###
