"""add day model

Revision ID: b900ff44af65
Revises: 413a3f767c6d
Create Date: 2026-03-09 09:54:11.391079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b900ff44af65'
down_revision: Union[str, None] = '413a3f767c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_days_org_id'), 'days', ['org_id'], unique=False)
    # Safe drop for audit_logs (idempotency fix — avoids crash if already dropped)
    for index_name in ['ix_audit_logs_event_type', 'ix_audit_logs_org_id', 'ix_audit_logs_user_id']:
        op.execute(f"""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = '{index_name}') THEN
                    EXECUTE 'DROP INDEX ' || quote_ident('{index_name}');
                END IF;
            END
            $$;
        """)
    op.execute("DROP TABLE IF EXISTS audit_logs CASCADE")
    op.add_column('queues', sa.Column('day_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_queues_day_id'), 'queues', ['day_id'], unique=False)
    op.create_foreign_key(None, 'queues', 'days', ['day_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queues', type_='foreignkey')
    op.drop_index(op.f('ix_queues_day_id'), table_name='queues')
    op.drop_column('queues', 'day_id')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['org_id'], unique=False)
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.drop_index(op.f('ix_days_org_id'), table_name='days')
    op.drop_table('days')
    # ### end Alembic commands ###
