"""update_queue_unique_constraint

Revision ID: ded3d8c4a14f
Revises: 7eee8683fe2a
Create Date: 2026-03-09 14:14:39.791349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ded3d8c4a14f'
down_revision: Union[str, None] = '7eee8683fe2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_queue_name_org', 'queues', type_='unique')
    op.create_unique_constraint('uq_queue_name_org_session', 'queues', ['name', 'org_id', 'session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_queue_name_org_session', 'queues', type_='unique')
    op.create_unique_constraint('uq_queue_name_org', 'queues', ['name', 'org_id'])
    # ### end Alembic commands ###
